import { Message } from "./Message.js";
import { QuiverPath } from "./QuiverPath.js";
import { QuiverRequest } from "./QuiverRequest.js";
import { QuiverResponse } from "./QuiverResponse.js";
import { QuiverExit } from "./QuiverExit.js";
import { QuiverError } from "./QuiverError.js";
import { QuiverSuccess } from "./QuiverSuccess.js";
import { QuiverRouter } from "./QuiverRouter.js";
import { QuiverRoute } from "./QuiverRoute.js";
import { QuiverClientRouter } from "./QuiverClientRouter.js";
import { QuiverClientRoute } from "./QuiverClientRoute.js";

export type QuiverContext = {
  address: string;
  received: Message;
  path?: QuiverPath;
  json?: unknown;
  request?: QuiverRequest;
  response?: QuiverResponse<unknown>;
  client?: QuiverClientRouter;
  resolver?: QuiverClientRoute;
  router?: QuiverRouter;
  route?: QuiverRoute;
  input?: unknown;
  output?: unknown;
  throw?: Omit<QuiverError, "id" | "ok">;
  return?: Omit<QuiverSuccess<unknown>, "id" | "ok">;
  exit?: Omit<QuiverExit, "id" | "ok">;
  error?: unknown;
  abort?: unknown;
  sent?: Message;
};
